name: Build Linux

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-linux.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-linux.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read
jobs:
  build-lto:
    runs-on: ubuntu-latest
    # not working on gcc-8 and gcc-9 see https://github.com/nodejs/node/issues/38570
    container: gcc:11
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          persist-credentials: false
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: |
          apt-get update && apt-get install ninja-build python-is-python3 -y
          ./configure --without-npm --without-corepack --ninja
          ninja -C out/Release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: node-binary-linux
          path: out/Release/node
