name: Build Linux

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-linux.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build-linux.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22'
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read
jobs:
  build-linux:
    runs-on: self-hosted
    # not working on gcc-8 and gcc-9 see https://github.com/nodejs/node/issues/38570 
    container: gcc:11
    env:
      CC: sccache gcc
      CXX: sccache g++
      SCCACHE_GHA_ENABLED: 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          persist-credentials: false
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@2e7f9ec7921547d4b46598398ca573513895d0bd  # v0.0.4
        with:
          version: v0.8.0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8  # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: |
          apt-get update && apt-get install ninja-build python-is-python3 cmake -y 
          ./configure --without-npm --without-corepack --ninja --enable-mimalloc --enable-lto
          ninja -C out/Release
      - name: Quick test
        run: ./out/Release/node -e 'console.log("test")'
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: node-linux-x64
          path: out/Release/node
          if-no-files-found: error
